- quanto/quantization/nn/__init__.py
- quanto/quantization/nn/qlayernorm.py
- quanto/quantization/nn/qlinear.py
- quanto/quantization/nn/qmodule.py
- quanto/quantization/qtensor.py
- quanto/quantization/quantize.py
- test/nn/test_custom_qmodule.py
This dfines a `QModuleMixin` and adds a decorator to register classes implementing it.
This paves the way to the quantization of the `GPT2` model, that uses a custom `Conv1d` layer.
This also adds a dispatch for `argmax`, required for greedy sample generation.
> Add basic mechanism to register a quantized module

- quanto/quantization/qtensor/ops.py
The `torch.ops.aten.cat` fallback to `float` in dispatch was generating recursive calls because the inputs were not dequantized.
This also adds support for the `torch.ops.aten.neg` operation.
> More fixes

- quanto/quantization/qtensor/core.py
- quanto/quantization/qtensor/func.py
- quanto/quantization/qtensor/ops.py
- test/qtensor/test_quantized_tensor.py
This was the root cause of all previous errors in the dispatched chain of operations: strides were always deduced from the shape of the data tensor, but this is incorrect when that tensor is non-contiguous.
Fixing that issue allows to remove the previous overloaded `contiguous/is_contiguous/matmul` methods to workaround the previous issues
> Set strides explicitly when creating a QTensor

- quanto/quantization/calibrate.py
- quanto/quantization/qtensor/ops.py
- quanto/quantization/quantize.py
- test/nn/test_custom_qmodule.py
This modifies `calibrate` to:
- allow momentum to be specified,
- add a calibration hook to track quantization errors per module,
- fix some inconsistencies between the calibration and standard quantized path. 
This also modifies `quantize` to allow to quantize only some lead modules.
Finally, this adds another dispatch.
> Improve calibration

- README.md
- quanto/quantization/calibrate.py
- quanto/quantization/nn/qlinear.py
- quanto/quantization/nn/qmodule.py
- quanto/quantization/qtensor/core.py
- quanto/quantization/qtensor/ops.py
- test/helpers.py
- test/nn/test_calibrate.py
- test/nn/test_qlinear.py
- test/qtensor/test_quantized_dispatch.py
- test/qtensor/test_quantized_tensor.py
This implements per-axis quantization of `QTensor` along a specific axis.
An additional parameter is added to the `calibration` context to allow the outputs of quantized modules to be quantized per-axis.
When this flag is set during calibration, the `QLinear` layers also quantize their weights per-axis.
Only the very simple MNIST example is today compatible with per-axis activations, with no real benefit as they are rescaled back per-tensor when reaching the next `QLinear`.
Other examples are not working since the view operation when splitting heads is today not compatible with per-axis input.
> Add support for per-axis quantization

- examples/nlp/text-generation/README.md
Here are the results:
```
|  model                           |  float |  per-tensor |  per-axis |
|----------------------------------|--------|-------------|-----------|
| facebook/opt-125m                | 0.61   | 0.03        | 0.59      |
| facebook/opt-350m                | 0.63   | 0.63        | 0.63      |
| facebook/opt-1.3b                | 0.72   | 0.46        | 0.72      |
| EleutherAI/pythia-160m           | 0.65   | 0.04        | 0.62      |
| EleutherAI/pythia-410m           | 0.71   | 0.19        | 0.56      |
| EleutherAI/pythia-1b             | 0.75   | 0.42        | 0.65      |
| princeton-nlp/Sheared-LLaMA-1.3B | 0.83   | 0.66        | 0.75      |
| NousResearch/Llama-2-7b-hf       | 0.92   | 0.54        | 0.66      |
```
> Add quantization results for several CausalLM models

- quanto/quantization/nn/qlinear.py
- quanto/quantization/nn/qmodule.py
- test/model/test_quantize_mlp.py
- test/nn/test_qlinear.py
- test/test_serialization.py
This mostly improves serialization tests and prepares further changes where the in_scale and out_scale might never be evaluated if we only quantize the weights.
> Improve serialization robustness

- examples/nlp/code-generation/quantize_code_model.py
- examples/nlp/text-classification/sst2/quantize_sst2_model.py
- examples/nlp/text-generation/quantize_causal_lm_model.py
- examples/vision/image-classification/mnist/quantize_mnist_model.py
- quanto/quantization/calibrate.py
- quanto/quantization/nn/qlayernorm.py
- quanto/quantization/nn/qlinear.py
- quanto/quantization/nn/qmodule.py
- quanto/quantization/qtensor/core.py
- quanto/quantization/qtensor/ops.py
- test/helpers.py
- test/model/test_quantize_mlp.py
- test/nn/test_calibrate.py
- test/nn/test_qlayernorm.py
- test/nn/test_qlinear.py
- test/qtensor/ops/test_linear_dispatch.py
- test/qtensor/ops/test_quantized_dispatch.py
- test/test_serialization.py
This modifies the QLinear and QLayernorm modules to only quantize the activations when the model has been calibrated, therefore allowing "weight-only" quantization.
This gives much better results than the "per-axis" activations, which will be removed in the next pull-request.
> Support weight only quantization

- .gitignore
- examples/nlp/text-generation/README.md
- examples/nlp/text-generation/evaluate_many_models.sh
- test/nn/test_qlinear.py
As expected, when quantizing only the weights of a generative model to int8, the accuracy seems to be preserved.
> Update causal LM results when quantizing only the weights

- examples/nlp/text-generation/README.md
- examples/nlp/text-generation/quantize_causal_lm_model.py
- quanto/quantization/nn/qlayernorm.py
- quanto/quantization/nn/qlinear.py
- quanto/quantization/qtensor/core.py
- quanto/quantization/quantize.py
- setup.sh
This fixes important issues with float16 models:
- overflows in core QTensor operations,
- conversion errors for some weights that were float32 instead.
This also introduces a change in quantize to mitigate memory issues with big models (might not be the final solution).
The examples are updated.
> Improve support of models with float16 weights

- quanto/quantization/qtensor/core.py
- quanto/quantization/qtensor/ops.py
- test/helpers.py
- test/qtensor/test_compile.py
This adds the two methods required to allow torch dynamo to trace graphs including QTensor.
This is not 100 % functional though:
- QTensor arguments and variables are correctly handled,
- QTensor can be instantiated from inside a dispatched operation,
- QTensor cannot be directly instantiated outside of an operation.
> Make QTensor traceable by torch dynamo

- quanto/quantization/nn/qlinear.py
- quanto/quantization/qtensor/core.py
- quanto/quantization/qtensor/ops.py
- test/helpers.py
- test/nn/test_calibrate.py
- test/nn/test_custom_qmodule.py
- test/nn/test_qlinear.py
- test/qtensor/ops/test_quantized_dispatch.py
- test/qtensor/test_absmax.py
- test/qtensor/test_compile.py
- test/qtensor/test_quantized_tensor.py
This improves `float8` testing in `QTensor`, still preparing `float8` activations.
> Add more float8 tests

- examples/nlp/text-classification/sst2/quantize_sst2_model.py
- examples/nlp/text-generation/evaluate_many_models.sh
- examples/nlp/text-generation/quantize_causal_lm_model.py
- examples/vision/image-classification/mnist/quantize_mnist_model.py
- quanto/quantization/calibrate.py
- quanto/quantization/nn/qlayernorm.py
- quanto/quantization/nn/qlinear.py
- quanto/quantization/nn/qmodule.py
- quanto/quantization/qtensor/func.py
- quanto/quantization/quantize.py
- test/helpers.py
- test/model/test_quantize_mlp.py
- test/nn/test_calibrate.py
- test/nn/test_qattention.py
- test/nn/test_qlayernorm.py
- test/nn/test_qlinear.py
- test/nn/test_qmodule.py
- test/qtensor/test_quantized_tensor.py
- test/test_serialization.py
This is a rather big change in terms of API, but not so much for now in terms of features, since for now weights are always quantized to `int8` and activations are either not quantized or quantized to `int8`.
This is to prepare the two big upcoming changes: `int4` quantization for weights and `float8` quantization for activations.
The ability to quantize activations per-axis is removed.
> Support weights and activations quantization mode configuration

- README.md
- examples/nlp/text-generation/README.md
- examples/nlp/text-generation/evaluate_many_models.sh
- examples/nlp/text-generation/quantize_causal_lm_model.py
- quanto/quantization/calibrate.py
- quanto/quantization/nn/qlinear.py
- quanto/quantization/qtensor/core.py
- quanto/quantization/qtensor/ops.py
- test/conftest.py
- test/helpers.py
- test/model/test_quantize_mlp.py
- test/nn/test_calibrate.py
- test/nn/test_qattention.py
- test/nn/test_qlayernorm.py
- test/nn/test_qlinear.py
- test/qtensor/test_quantized_tensor.py
This improves significantly the accuracy of some models, yet keeping the benefits of a lower device memory (as with int8 activations).
> Add support for float8 activations

- README.md
- external/smoothquant/README.md
- external/smoothquant/smoothquant.py
This modifies OPT or Bloom models to reduce the scale of the activations between consecutive layers using weights.
It does not work with any OPT model: this completely destroys the `facebook/opt-350m` model, which is the only model in the family with inverted norm.
When applied on the `facebook/opt-1.3b model`, it improves the accuracy of the model when using `int8` activations, but is still below the accuracy of the same model using `fp8_e4m3` activations.
> Add smoothquant export script

- README.md
- examples/nlp/text-generation/README.md
- examples/nlp/text-generation/quantize_causal_lm_model.py
This modifies the text-generation example to evaluate by default on the whole `lambada` test set, still calibrating with the `validation` set.
The results are a bit different, mostly better actually.
> More gen results

- README.md
- examples/nlp/text-generation/README.md
- quanto/quantization/qtensor/core.py
This applies the same fix that was only previously applied to the quantize operation to the rescale operation: avoid rounding when converting to float8.
Some of the results for NLP models are now even better.
> Fix float8 rescale

- quanto/qtensor/core.py
- quanto/qtensor/ops.py
- test/qtensor/ops/test_linear_dispatch.py
- test/qtensor/ops/test_mm_dispatch.py
- test/qtensor/ops/test_quantized_dispatch.py
- test/qtensor/test_compile.py
- test/qtensor/test_quantized_tensor.py
This refactors the declaration of dispatched operations to include declarative requirements on arguments (whether or not they should be QTensor, and which axis are allowed).
This allows to implement early fallbacks directly in the main dispatch method, which:
-  makes the framework more versatile (default to fallback instead of err if an op is not implemented),
-  simplifies the code of the dispatched operations, removing most of the checks.
We lose the ability to detect unsupported ops, but this could be implemented differently at calibration time.
> Improve dispatched op

- examples/nlp/text-generation/README.md
For LLama/Mistral models, the streamlining typically leads to MLP linear modules to use `float16` activations (since these modules outputs are either `silu` or `add`). I suspect this accounts for the most of the accuracy improvement.
> Update results with streamlined activations

- quanto/nn/qlinear.py
- quanto/qtensor/func.py
There is still no accelerated kernel for quantized inputs and weights with float bias, so the torch.nn.functional.linear call form QLinear will always end up being a separate matmul and bias.
This moves the decision at the function level to be able to change that in the future without refactoring QLinear.
> Intercept linear float bias at the function level

- bench/generation/benchmark.py
Tracking the peak memory allows to evaluate the influence of quantized activations on the device memory.
> Add peak memory in benchmark script

- quanto/tensor/core.py
- test/tensor/test_qbitstensor.py
Currently the int4 and int2 are stored in a int8 tensor which makes it not that memory efficient when quantizing the model
This PR introduces a new feature which is int4 / int2 weights packing in int32 in order to be more memory efficient at inference. 
Draft for now 
cc @dacorvo @SunMarc
> [`core`/ FEAT] Early version of pack / unpack int4 / int2 weights in uint8

- bench/library/benchmark.py
- pyproject.toml
- quanto/__init__.py
- quanto/library/__init__.py
- quanto/library/cpu/__init__.py
- quanto/library/cpu/unpack.cpp
- quanto/library/mps/__init__.py
- quanto/library/mps/unpack.mm
- quanto/library/ops.py
- test/library/test_unpack.py
This defines a `quanto` library allowing to define custom operations that can be dispatched per backend under `torch.ops.quanto`.
This also defines a new `torch.ops.quanto.unpack` operation.
Finally, this adds two pytorch extensions implementing `unpack` kernels:
- a standard `CPP` extension,
- an `MPS` extension.
A `CUDA` extension could be added later, but the `unpack` `CPP` implementation is compatible with `CUDA` devices.
Benchmarks:
Macbook AIR M2:
```
unpack_2bit[cpu]: torch = 110.026 ms, kernel = 72.452 ms, ratio = 1.5x
unpack_4bit[cpu]: torch = 56.668 ms, kernel = 34.530 ms, ratio = 1.6x
unpack_2bit[mps]: torch = 72.529 ms, kernel = 26.699 ms, ratio = 2.7x
unpack_4bit[mps]: torch = 39.967 ms, kernel = 11.151 ms, ratio = 3.6x
```
AWS `g5.2xlarge` (Nvidia A10):
```
unpack_2bit[cpu]: …
```
> Add quanto library and unpack kernels

- bench/library/benchmark.py
- quanto/library/cpu/__init__.py
- quanto/library/mps/__init__.py
- quanto/tensor/__init__.py
With the current implementation, backends are loaded whenever something is imported from `quanto`.
This modifies this to load backends dynamically the first time a library op is invoked.
> Only load backends when they are used

- README.md
Not calibrating will almost always result in disastrous output accuracy.
> doc: quantized activations require calibration

- README.md
> [`Doc`]: Fix typos in README.md

- bench/library/benchmark.py
- quanto/library/ops.py
When an exception occurs while calling an operation provided by an extension, we fallback to the default implementation.
The benchmark library script is also modified to take advantage of disable_extensions.
> Add fallback to library and refactor bench

- bench/library/benchmark.py
- quanto/library/ext/cpp/__init__.py
- quanto/library/ext/cpp/pybind_module.cpp
- quanto/library/ext/cpp/quantize.cpp
- quanto/library/ext/cpp/quantize.h
- quanto/library/ops.py
- quanto/library/python/__init__.py
- quanto/library/python/quantize.py
- test/library/test_quantize.py
This is mainly to test the library design with a different operation.
The `quantize_symmetric` operation simply rescales and maps the source tensor to either `int8` of `float8`.
The pull-request also includes a minimal C++ kernel for CPU devices, that only supports per-tensor `int8` quantization for now.
On a Macbook air, the optimized kernel is only 10 % faster than the default implementation using python torch operators.
> Add a quantize_symmetric operation and the corresponding CPU kernel

- quanto/library/ext/cpp/quantize.cpp
The compilation of the extension fails with some compilers.
> fix(cpp): address failing template deduction with some compilers

- bench/generation/benchmark.py
- quanto/nn/qlinear.py
By instantiating the QLinear weights directly on the device, it saves two copies: from device to cpu and back.
> fix(qlinear): speed up weights transfer

- bench/generation/benchmark.py
- quanto/library/ext/cpp/quantize.cpp
- quanto/library/python/unpack.py
- quanto/tensor/__init__.py
- quanto/tensor/core.py
- quanto/tensor/packed.py
- test/library/test_unpack.py
- test/tensor/test_compile.py
- test/tensor/test_packed_tensor.py
- test/tensor/test_qbitstensor.py
This modifies the QBitsTensor to use an underlying PackedTensor, and remove the restriction about the first dimension being a multiple of the number of packed values.
> QBitsTensor cleanup

- quanto/tensor/core.py
- quanto/tensor/func.py
- quanto/tensor/packed.py
- test/helpers.py
- test/nn/test_qlinear.py
- test/tensor/ops/test_qbitstensor_dispatch.py
- test/tensor/ops/test_qtensor_dispatch.py
There were several issues with `Tensor.to()` in `quanto` `Tensor` subclasses.
First, the `PackedTensor` and `QbitsTensor` dispatch for `Tensor.to()` were not implemented.
Second, when moving an entire `nn.Module`, `pytorch` does not only call `Tensor.to()` on the weight/bias, but also tries to do a shallow copy into the existing weight/bias.
Adding a proper dispatch at the function level to tag the `QTensor` class as incompatible with shallow copy solves the issue.
> Fix Tensor.to()

- README.md
- quanto/nn/__init__.py
- quanto/nn/qconv2d.py
- quanto/nn/qlayernorm.py
- quanto/nn/qlinear.py
- quanto/nn/qmodule.py
- test/nn/test_calibrate.py
- test/nn/test_qconv2d.py
- test/nn/test_qlinear.py
- test/nn/test_qmodule.py
This layer has a similar behaviour as `QLinear`. There is no accelerated quantized operations for convolutions, so its main use is to reduce on-device memory.
> Introduce Qconv2d

- quanto/tensor/func.py
- quanto/tensor/ops.py
- test/helpers.py
- test/nn/test_qlinear.py
- test/tensor/ops/test_linear_dispatch.py
- test/tensor/ops/test_mm_dispatch.py
- test/tensor/ops/test_qtensor_dispatch.py
- test/tensor/test_qbitstensor.py
- test/tensor/test_qtensor.py
This dispatch is not required since we never quantize biases.
> Remove linear aten dispatch

- quanto/tensor/ops.py
- quanto/tensor/qtype.py
- test/nn/test_qconv2d.py
- test/nn/test_qlinear.py
- test/tensor/ops/test_mm_dispatch.py
- test/tensor/ops/test_qtensor_dispatch.py
- test/tensor/test_qtensor.py
This simplifies the QTensor mm dispatch method to:
- restrict them to configurations actually used in `transformers` models,
- return a float Tensor instead of a `qint32` `QTensor`.
Eventually, these dispatched methods will not materialize the intermediate int32 Tensor, thanks to fused kernels.
The `qint16` and `qint32` `qtype` are removed.
> Simplify mm dispatch and remove qint16 and qint32

- quanto/tensor/core.py
- quanto/tensor/ops.py
This removes some overhead in the `mm` dispatch, which had increased the latency on all models.
The performances are now back to those advertized in the generation benchmark README.
> Cleanup mm dispatch

- bench/library/benchmark.py
- quanto/library/ext/cpp/__init__.py
- quanto/library/ext/cpp/mm.cpp
- quanto/library/ext/cpp/mm.h
- quanto/library/ext/cpp/pybind_module.cpp
- quanto/library/ops.py
- quanto/library/python/__init__.py
- quanto/library/python/mm.py
- quanto/tensor/ops.py
- test/library/test_mm.py
The implementation is identical to the python implementation, relying only on aten cpp operations.
This nevertheless brings a small performance improvement on all devices by avoiding going back to python in between the two ops.
> Add fused dequantize + mm cpp kernel

- examples/nlp/text-generation/quantize_causal_lm_model.py
- examples/vision/image-classification/mnist/quantize_mnist_model.py
- quanto/__init__.py
- quanto/library/ext/cpp/mm.cpp
- quanto/library/python/mm.py
- quanto/tensor/core.py
- test/nn/test_qlinear.py
The op was only compatible with types that can be promoted, and an error was raised with `float8` weights.
> Fix float8 weights in `dqmm` and release 0.0.13

- quanto/tensor/qbitstensor.py
This PR fixes a typo when copying the `zeropoint` value in ops like `.to(device)`. If a user moved the model after quantization, it could result in performance degradation. 
cc @younesbelkada
> fix zeropoint copy

- test/tensor/ops/test_linear_dispatch.py
- test/tensor/ops/test_mm_dispatch.py
- test/tensor/ops/test_qtensor_dispatch.py
The `assert_close` helper often fails when comparing small values, so it is removed and `assert_similar` is now used everywhere.
This should fix #105.
> Replace assert_close by assert_similar in tests

- README.md
- examples/nlp/text-classification/sst2/quantize_sst2_model.py
- examples/vision/image-classification/mnist/quantize_mnist_model.py
- pyproject.toml
- quanto/__init__.py
- quanto/calibrate.py
- quanto/nn/qconv2d.py
- quanto/nn/qlinear.py
- quanto/nn/qmodule.py
- quanto/serialization.py
- quanto/tensor/packed.py
- quanto/tensor/qbitstensor.py
- quanto/tensor/qtensor.py
- quanto/tensor/qtype.py
- test/model/test_quantize_mlp.py
- test/nn/test_qconv2d.py
- test/nn/test_qlinear.py
- test/nn/test_qmodule.py
This extends the `QModuleMixin` class to support two new serialization mode (in addition to the default `Pickle` mode):
- pytorch `weight_only` serialization (fixes #93),
- `safetensors` serialization (fixes #100).
> Safe serialization

- quanto/library/ext/__init__.py
- quanto/library/ext/cpp/__init__.py
- quanto/library/ext/cuda/README.md
- quanto/library/ext/cuda/__init__.py
- quanto/library/ext/cuda/pybind_module.cpp
- quanto/library/ext/cuda/unpack.cu
- quanto/library/ext/cuda/unpack.h
This creates a new quanto CUDA extension, adding a very simple unpack kernel.
Performances are greatly improved for the single unpack operation (x6 for int4, x4 for int2), but does not make a huge difference when running a full graph.
> Add CUDA unpack kernel

- bench/kernels/test_int_mm.py
- examples/nlp/text-generation/quantize_causal_lm_model.py
- quanto/tensor/ops.py
Originally submitted by @maktukmak as #126 
Regarding issue #64, torch now supports integer matmul (toch._int_mm) on the CPU at its master branch with this https://github.com/pytorch/pytorch/pull/121792 merged. Here, I made small changes to enable this kernel on quanto. To use the new backend, install torch nightly build after quanto.
> enable cpu integer matmul

- quanto/library/ext/cpp/__init__.py
- quanto/nn/qconv2d.py
- quanto/nn/qlayernorm.py
- quanto/nn/qlinear.py
- quanto/nn/qmodule.py
- quanto/tensor/__init__.py
- quanto/tensor/optimizers/__init__.py
- quanto/tensor/optimizers/absmax_optimizer.py
- quanto/tensor/optimizers/affine_optimizer.py
- quanto/tensor/optimizers/max_optimizer.py
- quanto/tensor/optimizers/optimizer.py
- quanto/tensor/optimizers/symmetric_optimizer.py
- quanto/tensor/qbitstensor.py
- quanto/tensor/qtensor.py
- test/model/test_quantize_mlp.py
- test/tensor/ops/test_mm_dispatch.py
- test/tensor/test_qbitstensor.py
- test/tensor/test_qtensor.py
By default quanto implements a simple absmax algorithm to evaluate the scale and zero-point to be used when quantizing QTensor and QBitsTensor. A refactoring was required in order to allow different algorithms.
All quantize methods at the torch.nn.Module or torch.Tensor level now accept an `optimizer: quanto.Optimizer` parameter.
This `quanto.Optimizer` object must be a `quanto.SymmetricOptimizer` when quantizing to 8-bit (`QTensor`), and a `quanto.AffineOptimizer` when quantizing to lower bitwidth.
implements #131
> Optimizers

- .github/workflows/conventional-commits.yml
- .github/workflows/python-examples.yml
- .github/workflows/python-quality.yml
- .github/workflows/python-tests.yml
- CONTRIBUTING.md
- pyproject.toml
This now only trigger the CI if all commits are compliant with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
> Check commits on pull-requests

- .github/workflows/conventional-commits.yml
- CONTRIBUTING.md
`merge` and `wip` are not allowed while `review` is.
> Update allowed conventional commits types

- .github/workflows/linux-cpu-tests.yml
- .github/workflows/linux-cuda-tests.yml
- pyproject.toml
- test/model/test_quantize_mlp.py
Since quantized operations are dispatched differently for each device, we need to add as many workflows as there are different devices.
> Add CI pipeline for NVIDIA GPUs

- quanto/quantize.py
In the `set_module_by_name` function, the process of returning `next_module` using a loop is replaced with `get_submodule`.
> refactor set_module_by_name

- .github/workflows/stale.yml
The stale bot cannot modify issues and pull-requests for now.
> ci: add permissions to stale bot

- .github/workflows/stale.yml
Add workflow_dispatch to allow to launch the stale bot manually.
> ci: allow manual stale bot

- bench/generation/README.md
This PR fixes a few links that redirect to the wrong file in the benchmark section.
> Fix benchmark links

- README.md
As a first step in the migration to [optimum](https://huggingface.co/docs/optimum/en/index), the repository has been renamed and the README updated.
> docs: explicitly reference optimum

- optimum/quanto/__init__.py
- optimum/quanto/library/ext/cuda/awq/v2/gemm_cuda.cu
- optimum/quanto/tensor/qbits/qbits.py
- test/library/test_mm.py
This modifies:
- the compilation of the library to include optimized kernels only if CUDA arch >= sm80,
- the QBitsTensor class to create optimized Tensors for these kernels only if CUDA arch >= sm80.
Fixes #207
> Only use optimized CUDA kernels if arch is at least sm80

- optimum/quanto/library/ext/cuda/__init__.py
- optimum/quanto/library/ext/cuda/awq/v2/gemm_cuda.cu
The __CUDA_ARCH__ preprocessor variable is not exported when compiling CUDA code for the host, but only for the device. This means that we need another preprocessor variable to decide whether we compile the AWQ kernels.
> feat(cuda): compile according to capabilities

- .github/workflows/python-examples.yml
- examples/vision/object-detection/quantize_owl_model.py
- optimum/quanto/tensor/qweight.py
- pyproject.toml
- test/tensor/test_qbytestensor.py
This pull-request fixes #192 and adds an object detection example based on owlv2 models.
The quantized model detections are equivalent to those of the float model when using int8, slightly different when using float8, and not so good using int4, although this can be improved by avoiding the quantization of the detection heads.
> Add owlv2 detection example

- optimum/quanto/library/ext/cpp/__init__.py
- optimum/quanto/library/ext/cuda/__init__.py
- optimum/quanto/library/ext/extension.py
- optimum/quanto/library/ext/mps/__init__.py
This first modifies the location of the cached built extensions to store them under the package directory.
This change will allow to fix broken installations by simply uninstalling and reinstalling the package.
This also modifies the extension build process to store the torch version when the extension was built: it is then checked when loading the extension and if it does not correspond to the current torch version the extension is rebuilt.
This will fix #194
> Extension lifecycle

- README.md
- examples/vision/image-classification/mnist/quantize_mnist_model.py
- optimum/quanto/__init__.py
- optimum/quanto/quantize.py
- pyproject.toml
This adds two paragraphs to explain quantized models serialization in README.
This also modifies the MNIST example to use `safe_save`, `safe_load` and `requantize`.
This addresses #136
> Add serialization in readme

- optimum/quanto/tensor/optimizers/__init__.py
- optimum/quanto/tensor/optimizers/hqq_optimizer.py
- test/tensor/optimizers/test_hqq_optimizer.py
This adds an `HqqOptimizer` that implements the algorithm described in "Half-Quadratic Quantization of Large Machine Learning Models", by Hicham Badri and Appu Shaji (https://mobiusml.github.io/hqq_blog/).
This is an adaption of the original implementation at https://github.com/mobiusml/hqq.
This optimizer is included more as an illustration than a real solution to address performance drop when quantizing models to `qint4` or `qint2`, as it often produces models that achieve a worse performance than the ones produced by the vanilla `MaxOptimizer` (this confirms some numbers reported by several research papers).
> Add HQQ optimizer

- .github/workflows/linux-cpu-tests.yml
- .github/workflows/linux-cuda-tests.yml
- optimum/quanto/models/__init__.py
- optimum/quanto/models/transformers_models.py
- optimum/quanto/subpackage/__init__.py
- optimum/quanto/subpackage/commands/__init__.py
- optimum/quanto/subpackage/commands/base.py
- optimum/quanto/subpackage/commands/quantize.py
- test/cli/cli_helpers.py
- test/cli/test_quantize_cli.py
This adds a `subpackage` module that registers `quanto` commands to `optimum` CLI.
The subpackage contains for now only a very simple `quantize` command.
```shell
$ optimum-cli -h
usage: optimum-cli
positional arguments:
{export,env,quanto}
export             Export PyTorch and TensorFlow models to several format.
env                Get information about the environment used.
quanto             Hugging Face models quantization tools
optional arguments:
-h, --help           show this help message and exit
```
```shell
$ optimum-cli quanto -h
usage: optimum-cli quanto [-h] {quantize} ...
positional arguments:
{quantize}
quantize  Quantize Hugging Face models.
optional arguments:
-h, --help  show this help message and exit
```
```shell
$ optimum-cli quanto quantize -h
usage: optimum-cli …
```
> Integrate quanto commands to optimum-cli

- optimum/quanto/library/ext/cuda/__init__.py
- optimum/quanto/library/ops.py
- optimum/quanto/tensor/qbits/qbits_ops.py
- optimum/quanto/tensor/qbits/tinygemm/qbits.py
- test/tensor/ops/test_linear_dispatch.py
- test/tensor/qbits/test_tinygemm_packed_tensor.py
- test/tensor/qbits/test_tinygemm_qbits_tensor.py
This fixes a few issues on CUDA with arch <= sm80: a TinyGemmQBitsTensor could be moved to the CUDA device without calling QBitsTensor::create.
A small change is also added to remove a dual dispatch for AWQ gemm. This slightly improves the decode latency for LLM (but does not impact much the end-to-end latency that is still dominated by the prefill latency).
> Fix TinyGemmQBitsTensor move

- examples/vision/text-to-image/quantize_pixart_sigma.py
- optimum/quanto/library/qbytes_mm.py
- optimum/quanto/tensor/optimizers/absmax_optimizer.py
- optimum/quanto/tensor/optimizers/symmetric_optimizer.py
- optimum/quanto/tensor/qtype.py
- optimum/quanto/tensor/qweight.py
- test/library/test_mm.py
This adds a simple example of quantization of a pixart sigma diffusers pipeline.
Both the `text_encoder` and `transformer` models of the pipeline are quantized.
This pull-request also fixes #231.
> Add pixart-sigma test to image example

- optimum/quanto/quantize.py
- optimum/quanto/tensor/qbits/qbits.py
- test/quantize/test_requantize.py
This fixes two issues that were raised by @sayakpaul in #255.
Known issue: the new requantize method shows increased device memory on the MPS device on the unit test for an fp16 model. This will be addressed in a separate pull-request.
> Fix serialization issues

- optimum/quanto/__init__.py
- optimum/quanto/models/__init__.py
The diffusers models classes were previously imported even if the library was absent.
> fix(models): correct check for diffusers

- optimum/quanto/quantize.py
I think the PR is self-explaining: you could not specify an include list in quantify, because include and exclude lists were swapped
> Fix a bug that prevents specifying include patterns for quantifying

- bench/torch_kernels/test_weight_int4pack_mm.py
- optimum/quanto/tensor/qbits/tinygemm/packed.py
Fixes: #274
PyTorch 2.5 adjusted input weights of _convert_weight_to_int4pack_cpu from `[n][k] int32` to `[n][k / 2] uint8`. Changing quanto code accordingly.
See: https://github.com/pytorch/pytorch/pull/129940
See: https://github.com/pytorch/pytorch/commit/6f662e95756333284450ff9c3c6e78c796aa6e77
CC: @dacorvo
> fix: adjust _convert_weight_to_int4pack_cpu input weights for pytorch>=2.5

- optimum/quanto/nn/qconv2d.py
- optimum/quanto/nn/qlayernorm.py
- optimum/quanto/nn/qlinear.py
- optimum/quanto/nn/qmodule.py
As raised by @latentCall145, there is a useless random weights initialization when quantizing a module.
The solution suggested in #290 is correct but makes the low-level quantization API depend on `accelerate`, which is only an optional dependency used by the high-level model API.
This is more or less the same implementation, but more explicitly using the `meta` device. Note that we need to explicitly preserve the scales, since unlike `accelerate`, pytorch does not distinguish between parameters and buffers when skipping initialization.
> Avoid random weights initialization when quantizing

- optimum/quanto/tensor/qbits/qbits.py
- optimum/quanto/tensor/qtensor.py
- optimum/quanto/tensor/weights/qbytes.py
- test/models/test_quantized_model_for_causal_lm.py
- test/models/test_quantized_model_for_pixart.py
- test/quantize/test_requantize.py
- test/tensor/qbits/test_qbits_instantiate.py
- test/tensor/qbits/test_qbitstensor_dispatch.py
- test/tensor/test_qbitstensor.py
- test/tensor/weights/test_weights_dispatch.py
- test/tensor/weights/test_weights_instantiate.py
This implements `QTensor.equal` and `torch.equal`, to allow an explicit comparison of quantized tensors.
Before that pull-request, comparing quantized tensors led to a fallback, ie dequantized tensors were compared.
This was slower, but most importantly this did not allow to verify if the quantized tensors were using the same packing (for configurations were optimized kernels must be used). 
This is especially useful when requantizing a serialized model to make sure it uses the optimized packing.
> Implement Tensor.equal and torch.equal for QTensor

- optimum/quanto/nn/qmodule.py
- optimum/quanto/tensor/qbits/packed.py
- optimum/quanto/tensor/qbits/qbits.py
- optimum/quanto/tensor/weights/qbytes.py
- test/models/test_quantized_model_for_causal_lm.py
Resolves #278
PyTorch allows to load state dicts with they strict=False argument to ignore missing keys. This is now also supported in optimum-quanto. Before this fix, a KeyError would be raised.
One context where this is important is for parameter-efficient fine-tuning adapters such as LoRA. There, we want to load only a small subset of parameters and leave the other model weights untouched. This requires non-strict loading.
Pull Request section?
to it if that's the case.
> FIX: Enable non-strict loading of state dicts

- bench/kernels/benchmark_marlin_fp8.py
- optimum/quanto/library/extensions/cuda/__init__.py
- optimum/quanto/library/extensions/cuda/marlin/COPYRIGHT
- optimum/quanto/library/extensions/cuda/marlin/fp8_marlin.cu
- optimum/quanto/library/extensions/cuda/marlin/fp8_marlin.cuh
- optimum/quanto/library/extensions/cuda/marlin/gptq_marlin.cuh
- optimum/quanto/library/extensions/cuda/marlin/gptq_marlin_dtypes.cuh
- optimum/quanto/library/extensions/cuda/marlin/gptq_marlin_repack.cu
- optimum/quanto/library/extensions/cuda/marlin/gptq_marlin_repack.cuh
- optimum/quanto/library/extensions/cuda/pybind_module.cpp
- optimum/quanto/nn/qmodule.py
- optimum/quanto/tensor/qbits/qbits.py
- optimum/quanto/tensor/qtensor.py
- optimum/quanto/tensor/weights/marlin/__init__.py
- optimum/quanto/tensor/weights/marlin/marlin.py
- optimum/quanto/tensor/weights/marlin/packed.py
- optimum/quanto/tensor/weights/qbytes.py
- optimum/quanto/tensor/weights/quantization.py
- test/library/test_mm.py
- test/nn/test_qattention.py
- test/nn/test_qlinear.py
- test/quantize/test_quantize_mlp.py
- test/tensor/qbits/test_awq_qbits_tensor.py
- test/tensor/weights/qbytes/test_marlin_qbytes_tensor.py
- test/tensor/weights/test_weights_instantiate.py
Since the introduction of mixed-precision fp16-int4 [MARLIN](https://github.com/IST-DASLab/marlin) (Mixed Auto-Regressive Linear) kernels by IST-DASLab, new mixed-precision MARLIN kernels have been introduced for other data types.
This adds the mixed-precision fp16/bf16-float8 kernels.
This is based on #241 by @fxmarty , with modifications to:
- remove an unwanted QLinear refactoring,
- make the models using the Marlin kernels differentiable,
- avoid breaking quantized weights serialization.
Known issue: there seems to be a slight accuracy drop when using the Marlin FP8 kernels as opposed to dequantizing the weights before the matmul. Maybe an overflow somewhere in the Marlin accumulation ?
> Add support for Marlin fp16/fp8 kernel (refactored)

- optimum/quanto/models/transformers_models.py
- optimum/quanto/nn/qmodule.py
- test/models/test_quantized_model_for_causal_lm.py
This fixes `QuantizedTransformerModel` inference to avoid omitting the lm_head (forward was always using the headless model).
This also fixes a minor bug that led to type mismatch on models with quantized activations that were not calibrated.
> Fix transformer model forward error

- optimum/quanto/library/qbytes_mm.py
The CPU implementation still has accuracy issues with pytorch 2.4.1.
> fix(library): disable int_mm for CPU

- .github/workflows/linux-cpu-tests.yml
- pyproject.toml
This bump the minimum python version to 3.9.
> chore: minimal python version is 3.9

- optimum/quanto/tensor/weights/qbits.py
- optimum/quanto/tensor/weights/qbytes.py
- optimum/quanto/tensor/weights/quantization.py
- test/helpers.py
- test/nn/test_qlinear.py
- test/tensor/weights/optimized/test_awq_weight_qbits_tensor.py
- test/tensor/weights/optimized/test_tinygemm_weight_qbits_tensor.py
- test/tensor/weights/test_weight_qbits_tensor_dispatch.py
This makes sure QTensor linear operations using optimized kernels are giving the same results as those using dequantized weights.
> Stricter optimized tensor tests

- optimum/quanto/library/extensions/cuda/__init__.py
- optimum/quanto/tensor/weights/marlin/fp8/packed.py
- optimum/quanto/tensor/weights/marlin/fp8/qbits.py
- test/library/test_mm.py
Using torch.library.custom_op introduces an overhead.
> refactor(library): reduce overhead in marlin op

- examples/nlp/text-generation/quantize_causal_lm_model.py
- optimum/quanto/models/transformers_models.py
Before this change `QuantizedTransformersModel` were not callable.
> Fix missing call in QuantizedTransformersModel

- .github/workflows/python-quality.yml
- Makefile
- examples/nlp/text-generation/quantize_causal_lm_model.py
- examples/vision/object-detection/quantize_owl_model.py
- external/awq/test_awq_kernels.py
- external/awq/test_awq_packing.py
- external/smoothquant/smoothquant.py
- optimum/quanto/library/extensions/extension.py
- optimum/quanto/models/diffusers_models.py
- optimum/quanto/models/transformers_models.py
- optimum/quanto/subpackage/commands/base.py
- optimum/quanto/tensor/activations/qbytes.py
- optimum/quanto/tensor/optimizers/absmax_optimizer.py
- optimum/quanto/tensor/optimizers/affine_optimizer.py
- optimum/quanto/tensor/optimizers/max_optimizer.py
- optimum/quanto/tensor/optimizers/optimizer.py
- optimum/quanto/tensor/optimizers/symmetric_optimizer.py
- optimum/quanto/tensor/qbits.py
- optimum/quanto/tensor/qbytes.py
- optimum/quanto/tensor/qtensor.py
- optimum/quanto/tensor/weights/marlin/fp8/qbits.py
- optimum/quanto/tensor/weights/qbits.py
- optimum/quanto/tensor/weights/qbytes.py
- pyproject.toml
- setup.sh
- test/library/test_quantize.py
- test/quantize/test_quantize_patterns.py
- test/tensor/weights/test_weight_qbits_tensor_quantize.py
Removed black configs, added black configs under ruff, ran ruff check and applied safe fixes
Fixes Issue #186 
Pull Request section?
to it if that's the case. -> Issue #186 
> Switched linters, black -> ruff

- bench/kernels/benchmark_w4a16.py
- optimum/quanto/library/extensions/cuda/__init__.py
- optimum/quanto/library/extensions/cuda/marlin/marlin_cuda.cpp
- optimum/quanto/library/extensions/cuda/marlin/marlin_cuda.h
- optimum/quanto/library/extensions/cuda/marlin/marlin_cuda_kernel.cu
- optimum/quanto/library/extensions/cuda/marlin/marlin_cuda_kernel.cuh
- optimum/quanto/library/extensions/cuda/pybind_module.cpp
- optimum/quanto/tensor/weights/marlin/__init__.py
- optimum/quanto/tensor/weights/marlin/int4/__init__.py
- optimum/quanto/tensor/weights/marlin/int4/packed.py
- optimum/quanto/tensor/weights/marlin/int4/qbits.py
- optimum/quanto/tensor/weights/marlin/permutations.py
- test/library/test_mm.py
- test/tensor/weights/optimized/test_awq_weight_qbits_tensor.py
- test/tensor/weights/optimized/test_marlin_int4_packed_tensor.py
- test/tensor/weights/optimized/test_marlin_int4_weight_qbits_tensor.py
- test/tensor/weights/test_weight_qbits_tensor_dispatch.py
- test/tensor/weights/weight_helpers.py
This adds a modified Marlin fp16/int4 kernel to the library and creates two new QTensor subclasses to use it:
- MarlinInt4PackedTensor,
- MarlinInt4WeightQBitsTensor.
There are issues with the weight/scales/zero-point readback as soon as parallelization increases. The consequence is that output features higher than 128 are corrupted when a sufficient amount of inputs are parallelized. 
As a consequence, the AWQ kernel is still used despite lower performances as the number of tokens increases.
The code is however merged as is, and #332  is created to investigate the issues.
> Add marlin int4 kernel

- optimum/quanto/library/extensions/cuda/__init__.py
- optimum/quanto/library/qbytes_mm.py
- optimum/quanto/nn/qlayernorm.py
- optimum/quanto/nn/qmodule.py
- optimum/quanto/tensor/weights/awq/packed.py
- optimum/quanto/tensor/weights/marlin/fp8/qbits.py
- optimum/quanto/tensor/weights/packing.py
- optimum/quanto/tensor/weights/qbytes.py
- optimum/quanto/tensor/weights/tinygemm/qbits.py
- test/tensor/activations/test_activations_compile.py
Most of the time, we want the resulting Tensor to be contiguous, so it is better to use reshape to enforce it.
Fixes #327
> fix: use reshape instead of view

- optimum/quanto/nn/qmodule.py
- test/nn/test_qlayernorm.py
When `elementwise_affine` is set to `False`, the `LayerNorm` does not have any `weight`.
This previously led to errors when trying to use the weight `dtype` or `device`.
Fixes #335
> Support QLayerNorm without weights

- optimum/quanto/library/qbytes_mm.py
- test/conftest.py
- test/helpers.py
- test/tensor/weights/weight_helpers.py
> [tests] enable testing for xpu (rebased)

- .github/workflows/linux-cuda-tests.yml
- .github/workflows/linux-examples.yml
- optimum/quanto/__init__.py
- optimum/quanto/library/extensions/mps/README.md
- optimum/quanto/tensor/weights/tinygemm/packed.py
- optimum/quanto/tensor/weights/tinygemm/qbits.py
- pyproject.toml
- test/tensor/activations/test_activations_compile.py
- test/tensor/test_packed_tensor.py
- test/tensor/weights/test_weight_qbits_tensor.py
- test/tensor/weights/test_weight_qbytes_tensor_serialization.py
There were some changes in the `pytorch` "internal" API that are incompatible between `2.5` and `2.6`. This bumps the minimum version and adapts to the new API.
> Bump minimal pytorch version to 2.6

- optimum/quanto/nn/qmodule.py
Trying to access the model state dict after using activation quantization throws an unexpected error. 
```
Traceback (most recent call last):
File "/home/dhruv/diffusers/../scripts/create_dummy_flux.py", line 42, in <module>
model.state_dict()
File "/home/dhruv/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2219, in state_dict
module.state_dict(
File "/home/dhruv/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2219, in state_dict
module.state_dict(
File "/home/dhruv/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2219, in state_dict
module.state_dict(
[Previous line repeated 1 more time]
File "/home/dhruv/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/nn …
```
> Fix error when trying to access `state_dict` after activation quantization

- test/tensor/activations/test_activations_compile.py
I guess it's a typo here. We should use inductor backend if the device is not MPS.
> fix compile backend

- tests/tensor/activations/test_activations_compile.py
After the release of pytorch 2.7, the compilation of graphs including dynamically quantized tensors is still not working.
The implementation should be reworked as the creation of tensor subclasses inside a graph should be supported since 2.6.
> test: disable activations compilation test

- optimum/quanto/tensor/weights/qbits.py
Hi @SunMarc . This commit should be included in #395 . Sorry for I forgot to push this commit. The shift is required to be int8 for awq linear in XPU. Please review it. Thanks!
> check shift before using awq linear on XPU
