huggingface/optimum-quanto

examples/nlp/text-generation/quantize_opt_model.py
quanto/quantization/qtensor/core.py
quanto/quantization/qtensor/func.py
quanto/quantization/qtensor/ops.py

The resulting quantized model is working, but has a really low accuracy when predicting the next input token for predefined sentences (0 %).
I am pushing this anyway because it includes a few fixes.

Add text-generation example with an OPT model

---

examples/nlp/code-generation/README.md
examples/nlp/code-generation/quantize_code_model.py

The actual accuracy of the quantized model, as compared to the float model is hard to evaluate because code generation models are not easy to evaluate.
For now we simply generate code from a random sample of the HumanEval dataset.

Add a codegen example

---

quanto/quantization/qtensor/core.py
quanto/quantization/qtensor/func.py
test/helpers.py
test/nn/test_qattention.py
test/qtensor/test_absmax.py
test/qtensor/test_compile.py
test/qtensor/test_quantized_tensor.py
test/test_serialization.py

This modifies the QTensor class to support non-integer internal data types, and adds a few float8 tests.

Preliminary float8 support

---

examples/nlp/text-generation/quantize_causal_lm_model.py
external/smoothquant/smoothquant.py

This modifies the smoothquant script to support also Llama based models.

Allow llama models to be statically smoothed

---

README.md
quanto/__init__.py

Version 0.0.11

---

CONTRIBUTING.md
pyproject.toml

These guidelines are heavily inspired by transformers guidelines.

Add contribution guidelines

---

.github/workflows/python-quality.yml
.github/workflows/python-tests.yml
test/tensor/test_compile.py

Add two CI workflows to check quality and run tests.

Add continuous integration

---

quanto/library/ext/README.md
quanto/library/python/README.md

This pull request adds a new text type to the project.
@dacorvo.

Add text type

---

bench/generation/README.md

doc(bench): fix links

---

bench/generation/perplexity.py

This merges the feature in #108 with a few changes.

Merge: change perplexity script

---

quanto/library/ext/cpp/unpack.cpp
quanto/tensor/packed.py
test/helpers.py
test/nn/test_qconv2d.py
test/nn/test_qlinear.py

We don't need to have two unpack methods, as pointed out by @SunMarc .

Remove duplicate unpack

---

examples/vision/StableDiffusion/READMD.md
examples/vision/StableDiffusion/quantize_StableDiffusion.py
examples/vision/StableDiffusion/requirements.txt

Pull Request for add quantize stablediffusion example   #170 
Pull Request section?
to it if that's the case.
@dacorvo Could you give me some feed back for this Pull Request

feat(example): add quantize stablediffusion example

---

quanto/tensor/func.py
test/nn/test_qlinear.py

By explicitly defining the backward path for the quantized linear function, we save calculations and prepare the introduction of fused operations for which we won't necessarily have a gradient.

Avoid composite gradients in quantized linear function

---

README.md

This simply explains why contributions will be suspended while we transition to `optimum`.

Announce migration to optimum

---

quanto/tensor/qbits.py
quanto/tensor/qbits_ops.py
quanto/tensor/qbytes.py
quanto/tensor/qtensor.py
quanto/tensor/qtensor_func.py

Just a small refactoring to clarify a bit the QTensor dispatch mechanism.

Clarify dispatch

---

Makefile
pyproject.toml

This adapts check and style rules to use the new `ruff check` paradigm.

Silence ruff warnings

---

optimum/quanto/library/ext/cuda/__init__.py

When multiple devices are detected, align on the maximum architecture to decide if we should compile AWQ kernels.

feat(awq): align extension on max arch

---

test/tensor/optimizers/test_hqq_optimizer.py
test/tensor/qbits/test_tinygemm_qbits_tensor.py

This cleans up some tests added by the previous two pull-requests.

Cleanup tests

---

optimum/quanto/library/qbytes_mm.py
test/tensor/ops/test_linear_dispatch.py

This fixes a regression introduced by a previous refactoring for fp16/bf16 int8 matrix multiplications when no kernels are available.

Fix float/int8 matrix multiplication latency regression

---

.github/workflows/linux-cpu-tests.yml
.github/workflows/linux-cuda-tests.yml
optimum/quanto/models/__init__.py
optimum/quanto/models/diffusers_models.py
optimum/quanto/models/shared_dict.py
optimum/quanto/models/transformers_models.py
test/models/test_quantized_model_for_pixart.py

Fixes https://github.com/huggingface/optimum-quanto/issues/252

feat: support diffusion models.

---

optimum/quanto/nn/qmodule.py
optimum/quanto/quantize.py

perf: faster and less memory-intensive model [re]quantization

---

README.md

Fixes small typos in the README and adds an import line for requantize to make the example clearer.
I've opened an issue about it as well: https://github.com/huggingface/optimum-quanto/issues/305

Fix README typos, add import line for requantize

---

bench/generation/evaluate_model.py
optimum/quanto/tensor/weights/awq/packed.py
optimum/quanto/tensor/weights/marlin/fp8/__init__.py
optimum/quanto/tensor/weights/marlin/fp8/packed.py
optimum/quanto/tensor/weights/packing.py
optimum/quanto/tensor/weights/reordering.py
test/tensor/weights/optimized/test_awq_weight_qbits_tensor.py
test/tensor/weights/optimized/test_marlin_fp8_packed_tensor.py

This is another pull-request that does some refactoring before the introduction of the Marlin int4 kernel.

More refactoring

---

bench/kernels/benchmark_w4a16.py
optimum/quanto/library/extensions/cuda/__init__.py
optimum/quanto/library/extensions/cuda/awq/v2/gemv_cuda.cu
optimum/quanto/tensor/weights/awq/qbits.py
test/library/test_mm.py

This cleans up the compilation flags and renames the library op to prepare the introduction of the Marlin op.

Refactor AWQ gemm

---

optimum/quanto/tensor/weights/qbytes.py

Fix lumina

---

optimum/quanto/library/extensions/__init__.py
optimum/quanto/library/extensions/cpp/__init__.py
optimum/quanto/library/extensions/cuda/__init__.py
optimum/quanto/library/extensions/extension.py
optimum/quanto/library/extensions/mps/__init__.py
test/helpers.py
test/library/test_extensions.py
test/library/test_mm.py
test/tensor/ops/test_linear_dispatch.py
test/tensor/weights/optimized/test_awq_weight_qbits_tensor.py
test/tensor/weights/optimized/test_marlin_qbytes_tensor.py
test/tensor/weights/optimized/test_tinygemm_packed_tensor.py

This slightly refactors extensions to prepare the introduction of the HIP extension.
This also reverts a change that was leading to tiny weights in unit tests.

Refactor extensions

---

optimum/quanto/models/transformers_models.py

fix https://github.com/huggingface/optimum-quanto/issues/355
I edited code inside local venv site-packages and it seems to work.
Pull Request section?
to it if that's the case.

Add repr for QuantizedTransformersModel

---

bench/torch_kernels/test_weight_int4pack_mm.py

Simular change as previously done in the library:
* https://github.com/huggingface/optimum-quanto/pull/373
CC: @dacorvo, @SunMarc

fix: apply cpu specific handling in int4pack benchmark

---

optimum/quanto/tensor/weights/tinygemm/packed.py

XPU _convert_weight_to_int4pack requires a reverse data layout of uint8 value.

fix tinygemm xpu
